CREATE TABLE TemporaryFiles (
    id CHAR(36) NOT NULL DEFAULT (UUID()),
    content BLOB NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    expires_at DATETIME NOT NULL DEFAULT (NOW() + INTERVAL 30 MINUTE),

    PRIMARY KEY(id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
