CREATE TABLE Stories (
    id int(11) UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    name varchar(32) NOT NULL UNIQUE,

    PRIMARY KEY(id),
    INDEX(name)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci PACK_KEYS=0;
