name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.14.0'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint
        
      - name: Build
        run: npm run build

      - name: Start MySQL service
        run: sudo systemctl start mysql.service

      - name: Test
        # This is just the default settings for GH Actions MySQL
        # Nothing secret here aside from the API key
        env:
          DB_TEST_HOSTNAME: 127.0.0.1
          DB_TEST_USERNAME: root
          DB_TEST_PASSWORD: root
          CDS_API_KEY: TEST_API_KEY
        run: npm run test

      - name: Check OpenAPI specs
        env:
          DB_HOSTNAME: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_NAME: test
          CDS_API_KEY: TEST_API_KEY
        run: |
          chmod +x scripts/test_openapi_specs.sh
          scripts/test_openapi_specs.sh ${DB_USERNAME} ${DB_PASSWORD} ${DB_NAME} ${DB_HOSTNAME}
