name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint
        
      - name: Build
        run: npm run build

      - name: Start MySQL service
        run: sudo systemctl start mysql.service

      - name: Test
        # This is just the default settings for GH Actions MySQL
        # Nothing secret here aside from the API key
        env:
          DB_TEST_HOSTNAME: 127.0.0.1
          DB_TEST_USERNAME: root
          DB_TEST_PASSWORD: root
          CDS_API_KEY: TEST_API_KEY
        run: npm run test

      - name: Check OpenAPI specs
        env:
          DB_HOSTNAME: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_NAME: test
          CDS_API_KEY: TEST_API_KEY
        run: |
          mysql -u ${DB_USERNAME} -p"${DB_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
          mysql -u ${DB_USERNAME} -p"${DB_PASSWORD}" ${DB_NAME} < src/sql/create_story_table.sql

          npm run start &
          sleep 10  # Give the app time to start up
          specs=("" "/hubbles_law")
          for spec in "${specs[@]}"; do
            url="http://localhost:8080${spec}/docs.json"
            echo $url
            DATA=$(curl $url)
            RESULT=$(curl -X "POST" \
              -H "Content-Type: application/json" \
              -d "$DATA" \
              https://validator.swagger.io/validator/debug)
            echo $RESULT
            echo $RESULT | jq -e '. == {}'
          done 
          pkill -f node
          mysql -u ${DB_USERNAME} -p"${DB_PASSWORD}" -e "DROP DATABASE ${DB_NAME};"
